### PR TITLE
fix: add not null checks to prevent running on destroyed activity

### LINKED ISSUE #1002: NullPointerException: 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
# Bug Report

### What is expected to happen?
Cordova should silently exit.

### What does actually happen?
Cordova crashes because the parent Activity is not alive anymore

## Information

Start a CordovaWebview and load a slow/large website.

`cordovaWebView.loadUrl(url)`

If you return to the previous activity (by using the (hardware) back button), cordova will try to execute `cordova.getActivity().runOnUiThread()`, but the activity is no longer there.

e.g., https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L187

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at org.apache.cordova.CordovaWebViewImpl$2.run(CordovaWebViewImpl.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### Command or Code

See information above on how to reproduce.

### Environment, Platform, Device

Android / All devices / All OS

### Version information

Android Studio 
Cordova 8.1.0

## Checklist

- [X] I searched for existing GitHub issues:
    Found issue: https://github.com/apache/cordova-android/issues/884 but this was closed due to lack of information
- [X] I updated all Cordova tooling to most recent version:
    Crash occured on 
    'org.apache.cordova:cordova:6.2.3'
    Updated to (crashed as well):
    'org.apache.cordova:framework:8.1.0'
- [X] I included all the necessary information above

### PR DESCRIPTION
**Pull request by secondVISION**
### Platforms affected
Android 

### Motivation and Context

See issue and sample MVP/Videos in : https://github.com/apache/cordova-android/issues/1002
Fixes #1002 

### Description

Added null pointer checks around ```cordova.getActivity()```, to check if the activity hosting Cordova is still alive.

### Testing

Updated MVP (see issue #1002 ) locally with these changes (also updated gradle but is not pushed in this PR).

### Checklist
- [ ] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 1]
```diff
@@ -176,22 +176,24 @@ public void run() {
                     e.printStackTrace();
                 }
 
-                // If timeout, then stop loading and handle error
-                if (loadUrlTimeout == currentLoadUrlTimeout) {
+                // If timeout, then stop loading and handle error (if activity still exists)
+                if (loadUrlTimeout == currentLoadUrlTimeout && cordova.getActivity() != null) {
```
Comment (breautek) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java:180]: I wonder if we should add an else condition to log a warning/debug statement when the activity no longer exists. This may help provide better insights for developers when they hit these edge cases unexpectedly.

e.g:

```java
if (loadUrlTimeout == currentLoadUrlTimeout && cordova.getActivity() != null) {
   ...
} else if (cordova.getActivity() == null) {
    LOG.d(TAG, "Cordova activity does not exists.");
}

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 2]
```diff
@@ -176,22 +176,24 @@ public void run() {
...
                 }
             }
         };
 
-        final boolean _recreatePlugins = recreatePlugins;
-        cordova.getActivity().runOnUiThread(new Runnable() {
-            public void run() {
-                if (loadUrlTimeoutValue > 0) {
-                    cordova.getThreadPool().execute(timeoutCheck);
+        if (cordova.getActivity() != null) {
```
Comment (breautek) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java:186]: If we do decide if logging debug statements is a good idea, then one should be also printed if this condition fails.

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 3]
```diff
@@ -238,7 +240,9 @@ public void showWebPage(String url, boolean openExternal, boolean clearHistory,
             } else {
                 intent.setData(uri);
             }
-            cordova.getActivity().startActivity(intent);
+            if (cordova.getActivity() != null) {
```
Comment (breautek) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java:243]: If we do decide if logging debug statements is a good idea, then one should be also printed if this condition fails.

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 4]
```diff
@@ -553,11 +557,13 @@ public void onPageFinishedLoading(String url) {
                     public void run() {
                         try {
                             Thread.sleep(2000);
-                            cordova.getActivity().runOnUiThread(new Runnable() {
-                                public void run() {
-                                    pluginManager.postMessage("spinner", "stop");
-                                }
-                            });
+                            if (cordova.getActivity() != null) {
```
Comment (breautek) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java:560]: If we do decide if logging debug statements is a good idea, then one should be also printed if this condition fails.

**Review by breautek — COMMENTED** [review]
Thank you for your PR.

I left a few comments, but I'm open minded. Let me know what you think.

Generally speaking I think this PR is :+1: I'll try to give this a more in-depth test later.

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java (hunk 1 above)
Comment (secondVISION) [reply framework/src/org/apache/cordova/CordovaWebViewImpl.java:180]: Ah sure, indeed. I'll add those logs!

**Comment by breautek** [comment]
I think the failure is a lie, I'll restart the checks.

**Comment by secondVISION** [comment]
Let me know if anything else is needed!

**Review by breautek — APPROVED** [review]

**Review by erisu — APPROVED** [review]
Code LGTM

**Comment by breautek** [comment]
Thank you for your contribution @secondVISION
