### PR TITLE
fix(prepare): delete splash screens if none are used

### LINKED ISSUE #1226: Default splash screens end up in APKs even if no splash screens are used
# Bug Report

### What is expected to happen?
The default splash screens are copied into the platform folder during the initial end up in release APK even if no splash screens are used by the app. Aside from about a megabyte of unnecessary clutter in the APK, this triggers the warnings described in #689 during release builds.

### What does actually happen?
Splashs should not be copied to `platforms/` if they are not used.

### Command or Code

This is reproducible using the default app:
1. `cordova create foo && cd foo`
2. `cordova platform add android`

If you run `du -ch platforms/android/app/src/main/res/*/screen.png` now, you will see the default splashs listed. Note that there are not splashs defined (cordova also emits a verbose log message about that during prepare: `This app does not have splash screens defined`). If you proceed to build those files will end up in the APK and cause aforementioned warnings if it is a release build.

### Version information
```
Cordova Packages:
    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.1
            serve: 4.0.0

Project Installed Platforms:
    android: 9.1.0

Project Installed Plugins:
    cordova-plugin-whitelist: 1.3.4

Environment:
    OS: Ubuntu 20.04.2 LTS (linux 5.4.0-72-generic) x64
    Node: v14.16.1
    npm: 7.11.2

```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by raphinesse**
### Motivation and Context

We copy default splash screens to the platform folder during platform creation. But then we do not delete them when the user uses no splash screens at all. This causes #1226 and what is described in #689.

Fixes #1226

### Description

The new implementation does not return early when updating splashes and none are defined. Instead, we let the cleanup map we create initially take care of deleting all unused splash screens. This also deletes the default splashes during the first prepare after platform creation.

### Testing

Manual testing on a default app.
A regression test would be great but I'm on a tight schedule. Feel free to add one if you feel like it.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]

File: bin/templates/cordova/lib/prepare.js [hunk 1]
```diff
@@ -328,10 +328,13 @@ function makeSplashCleanupMap (projectRoot, resourcesDir) {
...
 
-    // if there are "splash" elements in config.xml
+    // if there are no "splash" elements in config.xml
     if (resources.length === 0) {
         events.emit('verbose', 'This app does not have splash screens defined');
-        return;
+        // We must not return here!
+        // If the user defines no splash screens, the cleanup map will cause any
+        // existing splash screen images (e.g. the defaults that we copy into a
+        // new app) to be removed the app folder, which is what we want.
```
Comment (raphinesse) [inline bin/templates/cordova/lib/prepare.js:337]:
```suggestion
        // new app) to be removed from the app folder, which is what we want.
```

**Review by jcesarmobile — APPROVED** [review]
