### PR TITLE
javac error message fixes in requirements check

### LINKED ISSUE #618: JDK Download Url Is 404 When Clicked In VsCode
Got this error message:

```
> cordova run android
[cordova]  Android Studio project detected
[cordova]  Failed to run "javac -version", make sure that you have a JDK installed.
[cordova]  You can get it from: http://www.oracle.com/technetwork/java/javase/downloads.
[cordova]
[ERROR] An error occurred while running subprocess cordova.

        cordova run android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

Ctrl-clicking the link in vs-code opens up the url with the `.` on the end and is a 404 error.

Not sure if this is a vscode bug, but including the dot seems unnecessary and likely to trip up clients.

Raising it here for you to decide if it's an issue or not.

### PR DESCRIPTION
**Pull request by brodybits**
- fix download link
- put download link on its own line
- no punctuation at the end of the download link
  (fixes #618)
- no extra newline at the end
- extra newline spacing in case JAVA_HOME is invalid

in response to #618

I hope we can get this in before we cut the next major release for Cordova 9 (apache/cordova#10).

### CODE REVIEW

File: bin/templates/cordova/lib/check_reqs.js [hunk 1]
```diff
@@ -204,9 +204,11 @@ module.exports.check_java = function () {
             }, () => {
                 var msg =
                 'Failed to run "javac -version", make sure that you have a JDK installed.\n' +
```
Comment (rtpHarry) [inline bin/templates/cordova/lib/check_reqs.js]: Should it specifically say v8 / 1.8.* in this line as well?

Comment (brodybits) [reply bin/templates/cordova/lib/check_reqs.js]: Done as an additional change in PR #619.
