### PR TITLE
Prevent exit fullscreen mode from closing application 

### LINKED ISSUE #822: Back button event on full screen video closes application
# Bug Report

## Problem

As the title suggests, attempting to exit fullscreen using the back button, closes the application instead of exiting fullscreen.

1. Create a cordova application with a <video> element capable of going full screen.
2. Enter full screen mode on video
3. Hit back button

### What is expected to happen?

Full screen mode should be exited.

### What does actually happen?

Application is closed.

## Information

From what I could gather this is in fact a problem with Chrome itself, I've seen this occur on chrome versions (at least) higher than 74.0.3729.186 up to the current stable version (76.0.3809.132).

A [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=999212) on chromium bug tracker was also opened 

### Command or Code

N/A

### Environment, Platform, Device

Android, any version that uses Chrome as the webview provider and it has been updated.

### Version information
cordova cli: 7.1.0
cordova-android: 8.0.0

## Checklist

- [X] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

### PR DESCRIPTION
**Pull request by Chuckytuh**
### Platforms affected

Android

### Motivation and Context

This PR proposes a simple, quick, solution to overcome a problem with full screen mode that, when on and back button is pressed, the application is closed instead of exiting full screen. 

For more details see #822 and also https://bugs.chromium.org/p/chromium/issues/detail?id=999212

Fixes #822 

### Description

The custom view provided by WebKit on SystemWebChromeClients's `onShowCustomView` method is wrapped in a custom FrameLayout in order to be able to grab key events and redirect them into `SystemWebView`'s `dispatchKeyEvent`. 

Given that the custom view is the one with the focus, that's the one handling input, for this reason, we can hijack those key events and redirect them so that they end up closing the custom view because, as stated on the linked chromium bug ([#999212](https://bugs.chromium.org/p/chromium/issues/detail?id=999212)), the `onHideCustomView` method from the WebChromeClient subclass is not being executed for recent versions of Chrome, hence, not exiting full screen mode and instead, closing the MainActivity/ Application.

### Testing

Manual tests on a Pixel (Android 7.1.2) and Pixel 2 XL (Android 10) with Chrome updated to the most recent version.

### Checklist

- [X] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [X] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [X] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by breautek** [comment]
>full screen mode

When you say this, do you mean when the application has the `FullScreen` preference enabled? Or when you have a video player open and you hit the full screen button? Or both?

I'll try to test this tonight.

**Comment by itsvick** [comment]
@breautek Any update on this?
I have the same issue when pressing the fullscreen button from the video.

**Comment by Chuckytuh** [comment]
> When you say this, do you mean when the application has the FullScreen preference enabled? Or when you have a video player open and you hit the full screen button? Or both?

Sorry for the late reply, I meant full screen mode on html video player.

**Comment by patchon** [comment]
Hi, 

I recently stumbled on this on an application I'm developing. 
It uses a javascript video-player (plyr.js), and the problem is as described (back button from fullscreen exits the app). 

I've applied the commit https://github.com/apache/cordova-android/pull/823/commits/fdc4da591d03516d426daa67960ab50c6da20ae0 and now backbutton works as expected. 

*Almost anyway* :)

What happens is, 
- If I go fullscreen, then 
- Press backbutton, then 
- Press backbutton again 
- App exits (which it shouldn't since I have an handler registered that should popup a question if I really want to exit before exiting). 

It works correctly though, if you do it like this 
- If I go fullscreen, then 
- Press backbutton, then 
- Touches somewhere in the app (on the background for example), then 
- Press backbutton, 
- Registered handler popups a question whether I want to exit or not (ie. it works as expected).  

I have the following logs from logcat,
*Works correctly*  

```
2019-10-26 16:53:32.633 4042-4042/? D/LightBarController: onNavigationVisibilityChanged mNavigationLight = false
2019-10-26 16:53:32.643 4042-4042/? D/StatusBar: Status bar WINDOW_STATE_SHOWING
2019-10-26 16:53:32.644 4042-4042/? D/OverviewProxyService: SystemUi flags: 2
2019-10-26 16:53:32.646 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 2
2019-10-26 16:53:32.646 4042-4042/? D/OverviewProxyService: SystemUi flags: 2
2019-10-26 16:53:32.646 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 2
2019-10-26 16:53:32.646 4042-4042/? D/NavigationBar: Navigation bar WINDOW_STATE_SHOWING
2019-10-26 16:53:32.647 4042-4042/? D/OverviewProxyService: SystemUi flags: 0
2019-10-26 16:53:32.647 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 0
2019-10-26 16:53:33.121 4042-4042/? I/KeyButtonView: Back button event: ACTION_DOWN
    
    --------- beginning of system
2019-10-26 16:53:33.124 1277-5925/? D/VibratorService: vibrate from 'android', usageHint = 13
2019-10-26 16:53:33.172 4042-4042/? I/KeyButtonView: Back button event: ACTION_UP
2019-10-26 16:53:33.172 13826-22583/? D/TouchInteractionService: onBackAction#
2019-10-26 16:53:33.250 19090-19090/io.my-app D/SystemWebChromeClient: https://my-app/assets/js/navigation.js: Line 177 : Nothing to go back to, popping up exit dialog..
2019-10-26 16:46:55.697 18294-18314/io.my-app D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b70400a[MainActivity]
2019-10-26 16:46:55.709 18294-18294/io.my-app W/Choreographer: Already have a pending vsync event.  There should only be one at a time.
```

*Does not work correctly*  
```
2019-10-26 16:51:46.239 4042-4042/? D/LightBarController: onNavigationVisibilityChanged mNavigationLight = false
2019-10-26 16:51:46.260 4042-4042/? D/StatusBar: Status bar WINDOW_STATE_SHOWING
2019-10-26 16:51:46.262 4042-4042/? D/OverviewProxyService: SystemUi flags: 2
2019-10-26 16:51:46.262 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 2
2019-10-26 16:51:46.263 4042-4042/? D/OverviewProxyService: SystemUi flags: 2
2019-10-26 16:51:46.263 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 2
2019-10-26 16:51:46.263 4042-4042/? D/NavigationBar: Navigation bar WINDOW_STATE_SHOWING
2019-10-26 16:51:46.263 4042-4042/? D/OverviewProxyService: SystemUi flags: 0
2019-10-26 16:51:46.264 13826-22583/? D/TouchInteractionService: onSystemUiStateChanged# stateFlags: 0
2019-10-26 16:51:46.594 4042-4042/? I/KeyButtonView: Back button event: ACTION_DOWN
    
    --------- beginning of system
2019-10-26 16:51:46.597 1277-6554/? D/VibratorService: vibrate from 'android', usageHint = 13
2019-10-26 16:51:46.653 4042-4042/? I/KeyButtonView: Back button event: ACTION_UP
2019-10-26 16:51:46.654 13826-22583/? D/TouchInteractionService: onBackAction#
2019-10-26 16:51:46.661 1277-5925/? D/OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{9230f7c token=Token{f1f966f ActivityRecord{b3ce54e u0 com.teslacoilsw.launcher/.NovaLauncher t8082}}} pkgName com.teslacoilsw.launcher
2019-10-26 16:46:20.052 1277-4389/? D/OpSlaNetlinkHelper: frontPackageChanged: com.teslacoilsw.launcher uid:10136 pid:32020 | io.my-app uid:10298 pid:18294
2019-10-26 16:46:20.062 18294-18294/io.my-app D/CordovaActivity: Paused the activity.
2019-10-26 16:46:20.176 18294-18294/io.my-app D/CordovaActivity: Stopped the activity.
2019-10-26 16:46:20.177 18294-18294/io.my-app I/Surface: opservice is null false
2019-10-26 16:46:20.178 18294-18294/io.my-app D/CordovaActivity: CordovaActivity.onDestroy()
2019-10-26 16:46:20.178 18294-18294/io.my-app D/CordovaWebViewImpl: >>> loadUrl(about:blank)
2019-10-26 16:46:20.179 18294-18294/io.my-app W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
2019-10-26 16:46:20.196 18294-18294/io.my-app W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.c(PG:3)
        at org.chromium.android_webview.AwContents.T(PG:1)
        at Io.loadingStateChanged(PG:1)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

It seems like, when pressing the back button twice in a row (ie. not touching anything in the app between), it fires the fires the "stop activity" and then the "destroy activity", which is not the case when I press something in the app between the "back button presses".

Any ideas about this ? 
Are you able to reproduce it ?

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 1]
```diff
@@ -244,6 +244,22 @@ public void showWebPage(String url, boolean openExternal, boolean clearHistory,
         }
     }
 
+
```
Comment (erisu) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java]:
```suggestion
```

Remove extra new line here as there is already a new line above this one.

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 2]
```diff
@@ -497,8 +516,8 @@ public void handleDestroy() {
         public void clearLoadTimeoutTimer() {
             loadUrlTimeout++;
         }
-
         @Override
+
```
Comment (erisu) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java]:
```suggestion
```

Remove this newline.

File: framework/src/org/apache/cordova/CordovaWebViewImpl.java [hunk 3]
```diff
@@ -497,8 +516,8 @@ public void handleDestroy() {
         public void clearLoadTimeoutTimer() {
             loadUrlTimeout++;
         }
-
         @Override
```
Comment (erisu) [inline framework/src/org/apache/cordova/CordovaWebViewImpl.java]: Add back the newline above the `@Override` that was removed.

**Comment by timbru31** [comment]
@breautek - Unfortunately, the newlines around line 520 (`@Override`) are still off.

**Comment by Chuckytuh** [comment]
Formatting should be right now

**Comment by PhamNguyenNL** [comment]
Could you please create a new release/tag for this?

**Comment by timbru31** [comment]
Not an extra release, but cordova-android@9 will be released soonish.

**Comment by PhamNguyenNL** [comment]
Hope it's going to be released soon. Now I have to "npm i https://github.com/apache/cordova-android.git#master --save" manually in my cordova project to have it working every time add/remove the android platform.

**Comment by simion** [comment]
I need this fix too :) please release

**Comment by Hanzofm** [comment]
Hi @patchon,

For me still **not working** with cordova-android 9.0.0 where is merged this PR. Same problem of you with plyr.js.
